services:
  db:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: notes_app
    build: . # Builds from the Dockerfile in the current directory
    restart: always
    ports:
      - "${API_PORT:-8000}:8000" # Maps host port to container port 8000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db} # The service name of the database container
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
